apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: temporal
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:1.19
      nodeName: node1
